### PR TITLE
Fix bug improve code structure

### PR DESCRIPTION
**Pull request by Coding-Meet**
bug is you add text- field width fix define

i solved this problem

### CODE REVIEW

**Comment by its-me-debk007** [comment]
Can u please share the app here?

**Comment by Coding-Meet** [comment]
how can create apk in windows

**Comment by its-me-debk007** [comment]
Not the apk, but the standalone app!

Use the following command to create standalone app,
`./gradlew createReleaseDistributable`

The app will be present inside:
> build/compose/binaries/main-release/app/

**Comment by Coding-Meet** [comment]
> ./gradlew createReleaseDistributable

not work

image

**Comment by its-me-debk007** [comment]
Please double click this option, and share the output
image

**Comment by Coding-Meet** [comment]
image

**Comment by its-me-debk007** [comment]
I've checked the app. Works fine.
Nice feature of mentioning an example that u added!

Thanks for contributing :)

**Comment by Coding-Meet** [comment]
welcome

**Pull request merged**
